apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
  namespace: swiggy
  labels:
    app: swiggy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: swiggy
        image: dushyantkumark/swiggy-app:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
