apiVersion: v1
kind: Service
metadata:
  name: swiggy-app
  namespace: swiggy
  labels:
    app: swiggy-app
spec:
  selector:
    app: swiggy-app
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
